version: "3.7"
services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: "slack-message-finder-cloudflare"
    volumes:
      - ./cloudflare/prod:/home/nonroot/.cloudflared
    command: tunnel run

  db:
    image: postgres:13
    container_name: "slack-message-finder-db"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: "slack-message-finder-api"
    working_dir: /myapp/backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./vendor/bundle:/myapp/backend/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - ./settings/backend-prod.env

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: "slack-message-finder-frontend"
    volumes:
      - ./frontend/app:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "8000:12000"
    stdin_open: true
    tty: true
    env_file:
      - ./settings/frontend-prod.env

  bot:
    build:
      context: ./bot/
      dockerfile: Dockerfile
    container_name: "slack-message-finder-bot"
    volumes:
      - ./bot:/usr/src/app
    env_file:
      - settings/bot.env
    ports:
      - "9000:9000"
    command: ["python", "main.py"]

volumes:
  pgdata:
