version: "3"

tasks:
  default:
    desc: ""
    cmds:
      - task -l --sort none

  build:
    desc: This task is docker compose build
    cmds:
      - docker compose build
      - docker compose run --rm api bin/rails db:create
      - docker compose run --rm api bin/rails db:migrate
      - docker compose run --rm api bin/rails db:seed
      - docker compose up

  up:
    desc: This task is docker compose up
    cmds:
      - docker compose up

  down:
    desc: This task is docker compose down
    cmds:
      - docker compose down
